services:
  nginx:
    ports:
      - "80:80"

  postgres:
    ports:
      - "5454:5432"

  mysql:
    ports:
      - "3310:3306"

  # Mailpit для тестирования email (если понадобится)
  mailer:
    image: axllent/mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - catalog_network